### DISCUSSION TITLE
Bind mounts and permissions

### DISCUSSION THREAD

**Discussion by kyletozer** [BretFisher/ama#140] [Q&A]
Hi Bret,

First off, just wanted to thank you for the fantastic material in your Udemy Docker Mastery course! And second off, after starting to dabble with containers and setups, I've been running into an issue with permissions when using bind mounts in a compose setup.

Anything created inside of the container is created with the containers permissions rightfully so and I am unable to modify the file or files on the host until I change the permissions. I was just wondering if there is a way around always having to change permissions on my host when something is created in the container? The setup in question that I'm testing is an attempt at dockerizing WordPress for practice.

The idea was to create a development environment where I could keep my site files out of the container and easily be able to edit them on the host through volume bind mapping but this is the issue I keep running into, is there a better way of doing what I am trying to do?

Here are my configs:

docker-compose.yml
```
version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8889:80'

  wordpress:
    depends_on:
      - db
    image: wordpress:5.2
    volumes:
      - ./src:/var/www/html
    ports:
      - '8888:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data: {}
```
In the wordpress service, I am mapping the path to the wordpress installation in the container to the src folder in my project. Appreciate any help with this, Thanks again!
