### DISCUSSION TITLE
Test Docker Stack Example - container unable to communicate with Database container

### DISCUSSION THREAD

**Discussion by m0t0k0-2501** [BretFisher/ama#204] [Q&A]
So I wanted to try my own little example creating a stack.

So I decided to use osTicket's example from https://hub.docker.com/r/osticket/osticket

Where they give an example command to get going.

here is the example commands from the link above:

```
docker run --name osticket_mysql -d -e MYSQL_ROOT_PASSWORD=secret \
 -e MYSQL_USER=osticket -e MYSQL_PASSWORD=secret -e MYSQL_DATABASE=osticket mariadb

docker run --name osticket -d --link osticket_mysql:mysql -p 8080:80 osticket/osticket
```

Ok, so I wanted to take these commands and convert it to a stack .yml file, this is what I got.

```
version: '3.8'

services:

        osticket_mysql:
                image: mariadb
                environment:
                        - MYSQL_ROOT_PASSWORD=secret
                        - MYSQL_PASSWORD=secret
                        - MYSQL_USER=osticket

        osticket:
                image: osticket/osticket
                ports:
                        - "8080:80"
                environment:
                        - MYSQL_HOST=osticket_mysql
                        - MYSQL_USER=osticket
                        - MYSQL_PASSWORD=secret
```

So the issues I had was two-fold (maybe more)

1. I initially wanted to use swarm secrets, and it worked with the mariadb image, since they have environment variables that support _FILE named variables, but I don't think osTicket did.. so I just wrote the secret in the yml file just to try to get it working.

2. The only other issue I believe I had was under osticket environment variable for MYSQL_HOST, it didn't recognize the name osticket_mysql.. I kept getting an error saying that osticket couldn't connect to the database. ( i also named my stack osticket, so the services was named osticket_osticket and osticket_osticket_mysql, which i've even tried putting that as the MYSQL_HOST but that didn't work either )
I get the error:
Connecting to database mysql://osticket@osticket_mysql/osticket
************** INSTALLER FATAL ERROR ***************Database doesn't exist
****************************************************Die :(

After reading the docker documentation, I saw that link is going to be deprecated and they suggested I use networks, which in this case I believe a default network is already created which both services are a part of, so they should be able to communicate.

What am I doing wrong?
