### DISCUSSION TITLE
Advice on Potential Architecture

### DISCUSSION THREAD

**Discussion by evanlalo** [BretFisher/ama#220] [Q&A] [answered]
## Overview

I have been tasked with rebuilding a key piece of software for my company. The software is deployed on individual PCs across the country and each location only needs to be concerned with its own data. The app itself is pretty straightforward and consists of 3 containers running in a swarm.

- A react app
- Django backend
- MariaDB

I have added other containers for monitoring like prometheus, cAdvisor, promtail etc...

One main requirement of the app is that it can run offline. Meaning, even if a location looses external internet, the customer can still do their work.

My solution to this was to run the application on locahost, so as long as an intranet exists at the customer site, the app will work. I have verified and tested this. **What this means though, is that each location is running its own instance of the UI, backend and DB.**

Just as a sidenote, I can see why a native app might seem better but we have some requirements that make a PWA the best solution.

## Problems / Question

My main problem is how do I manage this? What's the best way to take care of deployments?

My first solution was to make each client location a master node. I would then have a cron job running on each PC to handle deployments. This actually works but I can see some major issues, especially once we scale up and it seems like a missed opportunity to take full advantage of everything docker swarm has to offer.

My second solution that I'm working on is have a master node(s) running on an EC2 instance and each location is a worker. This obviously makes deployments and management much simpler but I'm running into the following issues but **_only on the worker nodes_**.

1. I can't get UI to show on the worker nodes. I should be able to navigate to `http://localhost:8080/` but I keep getting "refused to connect". If I type in the public IP of my EC2 I can connect just fine.
2. My backend intermittently drops connection to the database.

FWIW here's the yaml file I'm using for the app stack.

```
version: '3.7'

secrets:
  loki_url:
    external: true

volumes:
  mysql_data:
  prometheus_data:


networks:
  app:
    name: app
    driver: overlay
    attachable: true

services:
  db:
    image: mariadb:10.7.3
    networks:
      - app
    secrets:
      - loki_url
    logging:
      driver: loki
      options:
        loki-url: /run/secret/loki_url
        loki-retries: 5
        loki-batch-size: 400
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
    env_file:
      - ../server/.env
    deploy:
      mode: global
      endpoint_mode: dnsrr

  django:
    depends_on:
      - db
    image: ${DJANGO_IMAGE}
    networks:
      - app
    secrets:
      - loki_url
    logging:
      driver: loki
      options:
        loki-url: /run/secret/loki_url
        loki-retries: 5
        loki-batch-size: 400
    environment:
      - CONTAINER=True
    env_file:
      - ../server/.env  
    deploy:
      mode: global

  frontend:
    depends_on:
      - django
    image: ${FRONTEND_IMAGE}
    networks:
      - app
    secrets:
      - loki_url
    logging:
      driver: loki
      options:
        loki-url: /run/secret/loki_url
        loki-retries: 5
        loki-batch-size: 400
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host      
    deploy:
      mode: global
```

## Conclusion

Any pointers, links or general advice would be a tremendous help. I have watched a lot of your talks and tutorials and I really appreciate your willingness to share your knowledge.

Regards,
