### DISCUSSION TITLE
How to run migrations in database inside Dockerfile using Node.js?

### DISCUSSION THREAD

**Discussion by deadcoder0904** [BretFisher/ama#232] [Q&A]
I've been trying to get Database migrations working in Drizzle + SQLite but have no luck so far.

I've had [questions](https://stackoverflow.com/q/78031427/6141587) that aren't solved. Like for example, `drizzle-orm` is not found because `node_modules` doesn't have a copy of it.

I tried using anonymous volumes as [suggested here](https://michalzalecki.com/docker-compose-node/) but despite doing that, I still get the same error when i try `docker logs nextjs-sqlite`:

```bash
> easypanel-nextjs-sqlite@0.1.0 db:migrate:prod
> node --env-file .env.production ./scripts/drizzle-migrate.mjs

node:internal/modules/esm/resolve:853
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'drizzle-orm' imported from /app/scripts/drizzle-migrate.mjs
    at packageResolve (node:internal/modules/esm/resolve:853:9)
    at moduleResolve (node:internal/modules/esm/resolve:910:20)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v20.11.1
```

### docker-compose.yml

```yml
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    # depends_on:
    #   db:
    #     condition: service_healthy
    #   redis:
    #     condition: service_started
    image: easypanel-nextjs
    container_name: nextjs-sqlite
    env_file:
      - .env.production
    ports:
      - 3000:3000
    volumes:
      - ./data:/data
      - /app/node_modules
  # migration:
  #   build:
  #     context: .
  #     dockerfile: docker/migrations/Dockerfile
  #   image: easypanel-nextjs
  #   depends_on:
  #     web:
  #       condition: service_completed_successfully
 ```

### Dockerfile

```dockerfile
FROM node:20-alpine AS base

# 1. Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat

RUN mkdir /app
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
COPY /src/app/db/migrations ./migrations

RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
  else echo "Lockfile not found." && exit 1; \
  fi
# USER node

# 2. Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
RUN chown -R node:node ./node_modules

COPY . .

# This will do the trick, use the corresponding env file for each environment.
COPY .env.production .env.production
RUN mkdir -p /data

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Create /data/users.prod.sqlite using Volume Mount
# RUN npm run db:migrate:prod
RUN npm run build

# 3. Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

COPY --from=builder /app/public ./public
# COPY --from=builder --chown=nextjs:nodejs /data /data

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Move the drizzle directory to the runtime image
COPY --from=builder --chown=nextjs:nodejs /app/src/app/db/migrations ./migrations

# Move the run script and litestream config to the runtime image
COPY --from=builder /app/scripts/drizzle-migrate.mjs ./scripts/drizzle-migrate.mjs
# COPY --from=builder /app/scripts/init.sh ./init.sh
COPY --from=builder /app/scripts/run.sh ./run.sh
# RUN chmod +x init.sh
RUN chmod +x run.sh

# Create data directory or else `npm run db:migrate:prod` will fail with TypeError: Cannot open database because the directory does not exist
# RUN mkdir -p /data

USER nextjs

EXPOSE 3000

# ENV PORT 3000
# ENV HOSTNAME localhost

# CMD ["npm", "run", "start"]
# ENTRYPOINT ["init.sh"]
RUN ls -la

CMD ["sh", "run.sh"]
```

### run.sh

```sh
#!/bin/bash
set -e

npm run db:migrate:prod & PID=$!
# Wait for migration to finish
wait $PID

echo "Starting production server..."
node server.js & PID=$!

wait $PID
```

I can't run migrations in dockerfile as it will build it in the image so `.sqlite` file won't be created.

I have to run it in the container just before I run my next.js server so `.sqlite` file gets created.

Locally, I do `npm run db:generate` to create `migrations/` folder & `npm run db:migrate` to create `users.dev.sqlite` which reads files from `migrations/` folder.

My basic goal is to get `*.sqlite` file in the production while using bind mount. But unsuccessful for a week.

Other ORMs do it easily like I found this blog that does it easily with Prisma + Nest -> https://notiz.dev/blog/prisma-migrate-deploy-with-docker

But I'm using Drizzle instead of Prisma which doesn't have a direct command like `prisma migrate deploy` so I have to run an npm script.

How would I do it?

I have a sample proof-of-concept -> https://github.com/deadcoder0904/easypanel-nextjs-sqlite (Next.js + Drizzle + SQLite + Docker)

My entire goal is to make SQLite file successfully created in production docker container. Unfortunately, there are no answers for Drizzle + Docker rather than complex hacks which I only found one person implement.

Is there a solution to this?
