### ISSUE TITLE
Multi stage (dev/prod) Node Dockerfile with Typescript

### ISSUE THREAD

**Issue by Glenny-Codifly** [BretFisher/ama#100]
Hi

I truly enjoyed your 2019 DockerCon talk about best practices for Docker Node apps. 

I solved the node_modules problem with an empty volume in my docker-compose and gracefully shutdown my server upon receiving SIGINT and SIGTERM. 

I was wondering how do I fit in TypeScript in this? Currently I solve this with `ts-node` but I would rather just use `tsc` through the stages since` ts-node` is not recommended in production use.

Dockerfile:
```
FROM node:14.2-slim AS prd
ENV NODE_ENV=production
EXPOSE 3000
RUN mkdir /app && chown -R node:node /app
WORKDIR /app
USER node
COPY --chown=node:node package.json yarn.lock ./
RUN yarn install --production --frozen-lockfile && yarn cache clean
COPY --chown=node:node . .
CMD ["node", "--require", "ts-node/register", "src/index.ts"]

FROM prd AS dev
ENV NODE_ENV=development
USER root
RUN yarn global add nodemon
USER node
CMD ["nodemon", "--config" , "nodemon.json"]
```

docker-compose.yaml:
```
version: '3.8'
services:
  api:
    build:
      context: ..
      dockerfile: ./env/Dockerfile
      target: prd
    ports:
      - '3000:3000'
    volumes:
      - ..:/app:delegated
      # Workaround to prevent host node_modules from getting mounted in container
      # Don't ever use the node_modules from the host
      - notused:/app/node_modules
    image: api
    container_name: api

volumes:
  notused:
```
nodemon.json:
```
{
  "watch": ["config", "src"],
  "ext": "ts,gql",
  "exec": "ts-node src/index.ts",
  "delay": 100
}
```

I was hoping you could give me some guidelines how to wire Typescript in this multi-stage Docker setup.

Kind regards

Glenny
