### ISSUE TITLE
node-docker-good-defaults -- Rookie guide to Environment Setup (Dev / Production / Test)

### ISSUE THREAD

**Issue by zipzit** [BretFisher/ama#2]
I recently discovered your repos, and I'm more than grateful for all the work you've done putting stuff together, particularly with the quality of documentation provided.   

I'm still improving my skills on this stuff, and guidelines like you've provided give great insight as to what's going on behind the scenes.  I've been playing with nodeJS deployments, but I will say I'm way confused by the whole environmental variables controlling different modes ( development / production / test / debug )...

Can you recommend to me a tutorial / posting / overview guide to help me get up to speed on what's going on there?
-- What's a development setup?  How do I update code and republish?  Risks to security if this version is used on production site?
-- What's production setup?  How do I update code and republish?  
-- Debug? Test?

I'm not asking you to teach me all the details here.  But, can you recommend to me the titles of the skill sets I need to learn, and links to references?

Again, many thanks.
LB

Reference:
For my particular issue, I'm working on an application for myself, which began with an [Express application generated](https://expressjs.com/en/starter/generator.html) structure, which I'm trying to squeeze into your [node-docker-good-defaults](https://github.com/BretFisher/node-docker-good-defaults) .  I'm totally lost in:

Dockerfile
```
# set our node environment, either development or production
# defaults to production, compose overrides this to development on build and run
ARG NODE_ENV=production
ENV NODE_ENV $NODE_ENV

# default to port 80 for node, and 5858 or 9229 for debug
ARG PORT=80
ENV PORT $PORT
EXPOSE $PORT 5858 9229
```

docker-compose.yml
```
services:
  node:
    build:
      context: .
      args:
        - NODE_ENV=development
    # you can use legacy debug config or new inspect
 ...
    #command: ../node_modules/.bin/nodemon --debug=0.0.0.0:5858
    command: ../node_modules/.bin/nodemon --inspect=0.0.0.0:9229
...
    environment:
      - NODE_ENV=development
```
(note to self:  the command line above is what actually starts the program running after $ `docker-compose up`. The program starts at index.js by default.  If using an alternate directory/filename.js the command line would be: `command: ../node_modules/.bin/nodemon ./directory/filename.js --inspect=0.0.0.0:9229` . )

package.json   
```
"scripts": {
    "start": "node index.js",
    "dev-docker": "../node_modules/nodemon/bin/nodemon.js --debug=5858",
    "dev-host": "nodemon --debug=5858"
  },
```

Ouch.. As I'm writing this question, it just now dawned on me... the key to getting started with this is understanding package.json scripts... you can run this in three different modes (actually two)... --debug-5858 is an environment variable.. at this point I'm going to let the question stand as is...  Again, Thx to you for whatever help you can provide.
